# This file defines the build pipeline to build SymCrypt in Azure Dev Ops. It defines multiple jobs
# for building and testing SymCrypt in each of the target environments. For more information on Azure
# Pipelines, see https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline

# Execute the pipeline whenever a change is made to master or publish
trigger:
- master
- publish

# Execute the pipeline on any PR into master or publish.
# (Currently not supported on Azure Git Repos; must be configured through the UI.)
pr:
- master
- publish

# List of jobs to build. Each job follows the same general format.
# 1. Windows AMD64 with CPU optimizations in Debug mode
# 2. Windows AMD64 with CPU optimizations in Release mode
# 3. Windows X86 with CPU optimizations in Debug mode
# 4. Windows X86 with CPU optimizations in Release mode
# 5. Linux AMD64 with CPU optimizations using GCC in Debug mode
# 6. Linux AMD64 with CPU optimizations using GCC in Sanitize mode
# 7. Linux AMD64 with CPU optimizations using GCC in Release mode
# 8. Linux AMD64 with CPU optimizations using clang in Debug mode
# 9. Linux AMD64 with CPU optimizations using clang in Sanitize mode
# 10. Linux AMD64 with CPU optimizations using clang in Release mode

# The following 2 jobs assume running on an AMD64 host, install cross compilation tools for Arm64 and runs a subset of units tests in QEMU
# 11. Linux Arm64 with CPU optimizations using clang in Debug mode
# 12. Linux Arm64 with CPU optimizations using clang in Release mode

# The following 4 jobs only run the unit tests on CI and PRs to publish (they are always built)
# 13. Windows 64b with no CPU optimizations in Release mode
# 14. Windows 32b with no CPU optimizations in Release mode
# 15. Linux with no CPU optimizations using GCC in Release mode
# 16. Linux with no CPU optimizations using clang in Release mode

jobs:
- job: Windows_AMD64_Debug
  pool:
    vmImage: 'windows-2019' # Windows Server 2019 with Visual Studio 2019
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: WindowsUserMode
      arch: AMD64
      cc: cl
      cxx: cl
      buildType: Debug
      additionalCMakeArgs: -DSYMCRYPT_INTERNAL_BUILD=1

- job: Windows_AMD64_Release
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: WindowsUserMode
      arch: AMD64
      cc: cl
      cxx: cl
      buildType: Release
      additionalCMakeArgs: -DSYMCRYPT_INTERNAL_BUILD=1

- job: Windows_x86_Debug
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: WindowsUserMode
      arch: X86
      cc: cl
      cxx: cl
      buildType: Debug
      additionalCMakeArgs: -DSYMCRYPT_INTERNAL_BUILD=1 -A Win32

- job: Windows_x86_Release
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: WindowsUserMode
      arch: X86
      cc: cl
      cxx: cl
      buildType: Release
      additionalCMakeArgs: -DSYMCRYPT_INTERNAL_BUILD=1 -A Win32

- job: Linux_AMD64_gcc_Debug
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: gcc
      cxx: g++
      buildType: Debug
      additionalCMakeArgs:

- job: Linux_AMD64_gcc_Sanitize
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: gcc
      cxx: g++
      buildType: Sanitize
      additionalCMakeArgs:

- job: Linux_AMD64_gcc_Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: gcc
      cxx: g++
      buildType: Release
      additionalCMakeArgs:

- job: Linux_AMD64_clang_Debug
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: clang
      cxx: clang++
      buildType: Debug
      additionalCMakeArgs:

- job: Linux_AMD64_clang_Sanitize
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: clang
      cxx: clang++
      buildType: Sanitize
      additionalCMakeArgs:

- job: Linux_AMD64_clang_Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: AMD64
      cc: clang
      cxx: clang++
      buildType: Release
      additionalCMakeArgs:

- job: Linux_QEMU_ARM64_clang_Debug
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: ARM64
      cc: clang
      cxx: clang++
      buildType: Debug
      additionalCMakeArgs:
      emulator: qemu-aarch64

- job: Linux_QEMU_ARM64_clang_Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: LinuxUserMode
      arch: ARM64
      cc: clang
      cxx: clang++
      buildType: Release
      additionalCMakeArgs:
      emulator: qemu-aarch64

- job: Generic_Windows_Win64_Release
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: Generic
      arch: Unknown
      cc: cl
      cxx: cl
      buildType: Release
      additionalCMakeArgs:

- job: Generic_Windows_Win32_Release
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Windows
      env: Generic
      arch: Unknown
      cc: cl
      cxx: cl
      buildType: Release
      additionalCMakeArgs: -A Win32

- job: Generic_Linux_gcc_Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: Generic
      arch: Unknown
      cc: gcc
      cxx: g++
      buildType: Release
      additionalCMakeArgs:

- job: Generic_Linux_clang_Release
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: azure-build-template.yml
    parameters:
      hostos: Linux
      env: Generic
      arch: Unknown
      cc: clang
      cxx: clang++
      buildType: Release
      additionalCMakeArgs:
